AllCops:
  Exclude:
    - 'bin/*'
    - Gemfile
    - Rakefile
    - config/**/*
    - 'vendor/**/*'
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Enabled: false
