AllCops:
  Exclude:
    - 'bin/*'
    - Gemfile
    - Rakefile
    - config/**/*
    - 'vendor/**/*'
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/decorators/concerns/translatable.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/decorators/concerns/translatable.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/support/matcher/translate_field_values_matcher.rb'

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
